/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SepoliaRouteImport } from './routes/sepolia'
import { Route as RealRouteImport } from './routes/real'
import { Route as FreeRouteImport } from './routes/free'
import { Route as IndexRouteImport } from './routes/index'

const SepoliaRoute = SepoliaRouteImport.update({
  id: '/sepolia',
  path: '/sepolia',
  getParentRoute: () => rootRouteImport,
} as any)
const RealRoute = RealRouteImport.update({
  id: '/real',
  path: '/real',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRoute = FreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/free': typeof FreeRoute
  '/real': typeof RealRoute
  '/sepolia': typeof SepoliaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free': typeof FreeRoute
  '/real': typeof RealRoute
  '/sepolia': typeof SepoliaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/free': typeof FreeRoute
  '/real': typeof RealRoute
  '/sepolia': typeof SepoliaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/free' | '/real' | '/sepolia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/free' | '/real' | '/sepolia'
  id: '__root__' | '/' | '/free' | '/real' | '/sepolia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreeRoute: typeof FreeRoute
  RealRoute: typeof RealRoute
  SepoliaRoute: typeof SepoliaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sepolia': {
      id: '/sepolia'
      path: '/sepolia'
      fullPath: '/sepolia'
      preLoaderRoute: typeof SepoliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real': {
      id: '/real'
      path: '/real'
      fullPath: '/real'
      preLoaderRoute: typeof RealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free': {
      id: '/free'
      path: '/free'
      fullPath: '/free'
      preLoaderRoute: typeof FreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreeRoute: FreeRoute,
  RealRoute: RealRoute,
  SepoliaRoute: SepoliaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
